apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ template "app.fullname" . }}
spec:
  tls:
    - secretName: app-certificate
      hosts:
        - hello-world-gke.app
  rules:
    - host: hello-world-gke.app
      http:
        paths:
          - backend:
              serviceName: {{ template "app.fullname" . }}
              servicePort: {{ .Values.port }}
            path: /
