apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: app-certificate
  namespace: default
spec:
  secretName: app-certificate
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
  commonName: hello-world-gke.app
  organization:
    - Hello World GKE CA
  dnsNames:
    - hello-world-gke.app
