apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: default
spec:
  secretName: ca-certificate
  issuerRef:
    name: self-signed-clusterissuer
    kind: ClusterIssuer
  isCA: true
  commonName: hello-world-gke-root-ca
